### ISSUE TITLE
post_number Error

### ISSUE THREAD

**Issue by PauliExklusor** [LiveSparks/SpaceBattlesCrawler#1]
`post_number` will throw an error in line 73, when >999. The input includes a thousands separator, i.e. a ",", and needs to be sanitized.

Suggestion:
`post_number = int(post_number.replace(',',''))`

**Comment by LiveSparks** [comment]
Thank you @PauliExklusor for pointing out the issue.
This has been fixed with commit bb6880d62fdb66af7f75e5767d209cc501c00ad4.
